name: Update Proxies Only

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: دریافت کد
        uses: actions/checkout@v4
        
      - name: نصب پایتون
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: نصب کتابخانه
        run: pip install requests
        
      - name: اجرای اسکریپت
        run: python update_and_build.py
        
      - name: ذخیره تغییرات
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add texts.txt config.json
          if ! git diff --staged --quiet; then
            git commit -m "Auto update $(date '+%H:%M')"
            git push
          fi
